---
title: "FASTR Sampling location map"
author: "Dave Bosworth and Nicole Kwan"
date: "6/21/2021"
output: 
  html_document: 
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose


# Global code and functions

```{r load packages, message = FALSE, warning = FALSE}
# Load packages
library(tidyverse)
library(sf)
library(leaflet)
```


# Import and Prepare Data

```{r import data, message = FALSE}
df_samp_loc <- read_csv("Stations_Fish_NDFA_2021-01-13.csv")
```

```{r convert df to sf}
sf_samp_loc <- df_samp_loc %>% 
  select(-geometry) %>% 
  st_as_sf(
    coords = c("Longitude", "Latitude"),
    crs = 4326,
    remove = FALSE
  )
```

```{r split up sf}
# Create 3 different sf objects by data type
# Fish stations:
sf_samp_loc_fish <- sf_samp_loc %>% 
  filter(!Survey.x %in% c("EMP", "NDFA", "USGS")) %>% 
  mutate(
    Type = case_when(
      Survey.x %in% c("EDSM", "FMWT", "Townet") ~ "Tow",
      Survey.x %in% c("DJFMP", "Yolo") ~ "Seine",
      TRUE ~ "Rescues"
    )
  )

# WQ stations:
sf_samp_loc_wq <- sf_samp_loc %>% filter(Survey.x %in% c("EMP", "NDFA", "USGS"))

# Lower Trophic stations:
sf_samp_loc_lt <- sf_samp_loc %>% 
  filter(
    Survey.x == "NDFA",
    !StationCode %in% c("DWT", "SHR", "WWT")
  )
```

```{r create leaflet map}
# Define color palette for Surveys
color_pal <- colorFactor(palette = "plasma", domain = fish_samp_loc_sf$Survey.x)

leaflet(fish_samp_loc_sf) %>% 
  addTiles() %>% 
  addCircleMarkers(
    radius = 3,
    fillColor = ~color_pal(Survey.x),
    fillOpacity = 1,
    weight = 0.5,
    color = "black",
    opacity = 1,
    label = paste0(
      "Station: ",
      fish_samp_loc_sf$StationCode,
      ", Survey: ",
      fish_samp_loc_sf$Survey.x
    )
  ) %>% 
  addLegend(
    position = "bottomleft",
    pal = color_pal,
    values = ~Survey.x,
    title = "FASTR Fish Surveys"
  )
```

